// Copyright (c) 2018 Jabiru Ventures LLC
// Licensing questions should be addressed to jvlicense@jabiruventures.com
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------
// Generated by the `tools` package.
#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .Call calls */
extern SEXP addInt64Int(SEXP, SEXP);
extern SEXP addInt64Int64(SEXP, SEXP);
extern SEXP charToInt64(SEXP, SEXP);
extern SEXP doubleToInt64(SEXP);
extern SEXP int64ToChar(SEXP);
extern SEXP int64ToDouble(SEXP);
extern SEXP int64ToHex(SEXP);
extern SEXP int64ToInteger(SEXP);
extern SEXP isInt64NA(SEXP);
extern SEXP readCSV(SEXP);
extern SEXP subInt64Int64(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"addInt64Int",    (DL_FUNC) &addInt64Int,    2},
    {"addInt64Int64",  (DL_FUNC) &addInt64Int64,  2},
    {"charToInt64",    (DL_FUNC) &charToInt64,    2},
    {"doubleToInt64",  (DL_FUNC) &doubleToInt64,  1},
    {"int64ToChar",    (DL_FUNC) &int64ToChar,    1},
    {"int64ToDouble",  (DL_FUNC) &int64ToDouble,  1},
    {"int64ToHex",     (DL_FUNC) &int64ToHex,     1},
    {"int64ToInteger", (DL_FUNC) &int64ToInteger, 1},
    {"isInt64NA",      (DL_FUNC) &isInt64NA,      1},
    {"readCSV",        (DL_FUNC) &readCSV,        1},
    {"subInt64Int64",  (DL_FUNC) &subInt64Int64,  2},
    {NULL, NULL, 0}
};

void R_init_csvread(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
